### ISSUE TITLE
Why do I get "Skpped" when trying to convert all files in folder?

### ISSUE THREAD

**Issue by colibris79** [thingsiplay/tochd#8]
Hi! 
First of all, thanks for the tool! 
I am using tochd v0.13 with Mint 21.3 (Ubuntu 22.04), installed the script and I can convert an individual file to .chd it works without any issues. But when I run the command inside a folder with several .iso files, I will get "Skipped" for all of them. I have tried different options but I haven't been able to make it work. I am sure it may be something quite simple, but I still wasn't able to make it work  : (
Any suggestions?

**Comment by colibris79** [comment]
Ok. Yes, it was something quite silly, had typed wrong the *.iso. 
So "tochd *.iso" (and with any other options) works fine

**Comment by thingsiplay** [comment]
You're welcome, and glad you figured it out. You can also just do `tochd *`, and give all files over. The script will figure out which files are supported and not and what has been converted already. In example it skips, if there is already same file but with `.chd` extension already.

Instead files, you can also give a directory, which tochd will find all files in that directory and do the same as described above. For current folder it is enough to use the dot like `tochd .` .

These are just suggestions, in case you didn't know about.
